class SportsInfo{
  final int position;
  final String name;
  final String iconImage;
  final String descprition;

  SportsInfo(
    this.position,{
      this.name,
      this.descprition,
      this.iconImage,
    }
  );
}

List<SportsInfo> sports = [
  SportsInfo(1,
    name: 'Cricket',
    iconImage: "assets/cricket.jpg",
    descprition: "Cricket is a bat-and-ball game played between two teams of eleven players",
    ),
   SportsInfo(1,
    name: 'Football',
    iconImage: "assets/cricket.jpg",
    descprition: "Bat Ball",
    ),
    SportsInfo(1,
    name: 'Basketball',
    iconImage: "assets/cricket.jpg",
    descprition: "Bat Ball",
    ),
    SportsInfo(1,
    name: 'Kabaddi',
    iconImage: "assets/background.jpg",
    descprition: "Bat Ball",
    ),
    SportsInfo(1,
    name: 'Table Tennis',
    iconImage: "assets/background.jpg",
    descprition: "Bat Ball",
    ),
    SportsInfo(1,
    name: 'Athletics',
    iconImage: "assets/background.jpg",
    descprition: "Bat Ball",
    ),
    SportsInfo(1,
    name: 'Badminton',
    iconImage: "assets/background.jpg",
    descprition: "Bat Ball",
    ),
    SportsInfo(1,
    name: 'Powerlifting',
    iconImage: "assets/background.jpg",
    descprition: "Bat Ball",
    ),
    SportsInfo(1,
    name: 'Carrom',
    iconImage: "assets/background.jpg",
    descprition: "Bat Ball",
    ),
    SportsInfo(1,
    name: 'Chess',
    iconImage: "assets/background.jpg",
    descprition: "Bat Ball",
    ),
    SportsInfo(1,
    name: 'Tug of War',
    iconImage: "assets/background.jpg",
    descprition: "Bat Ball",
    ),
    SportsInfo(1,
    name: 'Pool',
    iconImage: "assets/background.jpg",
    descprition: "Bat Ball",
    ),
    SportsInfo(1,
    name: 'Kho Kho',
    iconImage: "assets/background.jpg",
    descprition: "Bat Ball",
    ),
    SportsInfo(1,
    name: 'Volleyball',
    iconImage: "assets/background.jpg",
    descprition: "Bat Ball",
    ),
    SportsInfo(1,
    name: 'Obstacle Race',
    iconImage: "assets/background.jpg",
    descprition: "Bat Ball",
    ),
     
];